### PR TITLE
Add an `inputBox` component

### PR DESCRIPTION
**Pull request by christian-withjoy**
Also, fix for problem breaking storybook,

### CODE REVIEW

**Comment by ktranada** [comment]
@christian-withjoy merge conflicties

**Comment by christian-withjoy** [comment]
@ktranada FIXED

**Comment by christian-withjoy** [comment]
@ktranada requested screenshot of component
screen shot 2018-01-17 at 4 33 47 pm
It's an `input`, that is a box, thus `InputBox`. This is from a long time ago and we had a whole discussion about what constitutes an `InputLine` vs and `InputBox`

**Comment by ktranada** [comment]
i imagine that we won't always have it be center aligned - maybe have a `alignText` prop?

**Pull request closed without merging**
